### ISSUE TITLE
Nai3官方Api修正导致的报错

### ISSUE THREAD

**Issue by 18833580325** [wochenlong/nai3_train#11]
报错信息:
G:\novelai\tieba\SD-WebUI\stable-diffusion-webui-master\outputs\nicejob\nai3\nai3_train-main\newest\nai3_train-main>python random_characetrs.py
Traceback (most recent call last):
  File "G:\novelai\tieba\SD-WebUI\stable-diffusion-webui-master\outputs\nicejob\nai3\nai3_train-main\newest\nai3_train-main\random_characetrs.py", line 144, in <module>
    image_data = generator.generate_image("prefix_", random_mode=random_mode)
  File "G:\novelai\tieba\SD-WebUI\stable-diffusion-webui-master\outputs\nicejob\nai3\nai3_train-main\newest\nai3_train-main\random_characetrs.py", line 111, in generate_image
    with zipfile.ZipFile(io.BytesIO(r.content), mode="r") as zip:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

可能的问题:
API 响应问题：requests.post 请求的 API 可能没有返回预期的 ZIP 文件。可能是因为请求出错，或者 API 的行为已经改变，不再返回 ZIP 格式的内容。

请求失败处理：如果请求失败（例如，因为网络问题或 API 限制），r.content 可能不包含有效的 ZIP 数据。在尝试将 r.content 作为 ZIP 文件打开之前，应该检查请求的响应状态码 r.status_code 是否为 200（表示成功）。

**Comment by wochenlong** [comment]
官方api似乎修改为：image.novelai.net/ai/generate-image 
![3a9a5ed51b2cb8c1a01711befcf0a71f](https://github.com/wochenlong/nai3_train/assets/117965575/ff583836-95e7-4d6d-8e3f-e02e80620a1d)

**Comment by 18833580325** [comment]
![M$H1F28HSX`8TW$ 0_ ATRV](https://github.com/wochenlong/nai3_train/assets/80527930/a468b0f8-ba00-41cc-8284-44d024eb40b9)
设置了一下self.api = "https://api.novelai.net/ai/generate-image",运行后还是报错TUT

**Comment by borntree** [comment]
请求的json参数改为如下内容
"input": "",
            "model": "nai-diffusion-3",
            "action": "generate",
            "parameters": {
                "params_version": 1,
                "width": 832,
                "height": 1216,
                "scale": 6,
                "sampler": "k_euler_ancestral", # k_euler_ancestral  k_euler
                "steps": 28,
                "seed": 0,
                "n_samples": 1,
                "ucPreset": 3,
                "qualityToggle": True,
                "sm": True,
                "sm_dyn": True,
                "dynamic_thresholding": False,
                "controlnet_strength": 1,
                "legacy": False,
                "add_original_image": False,
                "uncond_scale": 1,
                "cfg_rescale": 0,
                "noise_schedule": "native",
                "legacy_v3_extend": False,
                "reference_information_extracted": 1,
                "reference_strength": 0.6,
                "negative_prompt": negative_prompt,

请求的url改为https://image.novelai.net/ai/generate-image

我推测是之前请求参数内的布尔值为文本导致的，没实测，不过目前我是可以用的

**Comment by borntree** [comment]
对了，我用的代码优化之前的，因为我只用一个文件的原因，没去更新。

**Comment by borntree** [comment]
[characetrs_expression.txt](https://github.com/wochenlong/nai3_train/files/14933986/characetrs_expression.txt)

**Comment by 18833580325** [comment]
> [characetrs_expression.txt](https://github.com/wochenlong/nai3_train/files/14933986/characetrs_expression.txt)

OK啦,辛苦辛苦♥(顺带一提项目的json可以更新下啦,和脚本里有不少对不上)
