### ISSUE TITLE
API请求异常错误

### ISSUE THREAD

**Issue by zJyheSyXq5** [wochenlong/nai3_train#12]
官方是否修改了API 我的程序现在会提示 “请求出现异常: 404 Client Error: Not Found for url: https://api.novelai.net/ai/generate-image”  我查到在X上官方说 将图像生成相关端点从标准NovelAI API [http://api.novelai.net] 中分离出来，将所有图像生成相关方面移动到 [http://image.novelai.net] 但是我按照说明替换程序中的API后会报  “请求出现异常: 400 Client Error: Bad Request for url: https://image.novelai.net/ai/generate-image” 不知道该如何改正

**Comment by wochenlong** [comment]
官方api似乎修改为：image.novelai.net/ai/generate-image  
![3a9a5ed51b2cb8c1a01711befcf0a71f](https://github.com/wochenlong/nai3_train/assets/117965575/a8a9559c-312a-412d-830c-f73008ea9d66)

**Comment by zJyheSyXq5** [comment]
修改API后会会报 “请求出现异常: 400 Client Error: Bad Request for url: https://image.novelai.net/ai/generate-image”

**Comment by zJyheSyXq5** [comment]
对照了其他项目 找到问题了在   json_ = {
    "input": "",  # 设置请求的输入文本
    "model": "nai-diffusion-3",  # 设置模型名称
    "action": "generate",  # 设置动作为生成图像
    "parameters": {
        "width": 832,  # 设置生成图像的宽度
        "height": 1216,  # 设置生成图像的高度
        "scale": 5,  # 设置图像的缩放比例
        "sampler": "k_euler",  # 设置采样器类型
        "steps": 28,  # 设置生成图像的步数
        "seed": 0,  # 设置生成图像的随机种子
        "n_samples": 1,  # 设置生成图像的样本数
        "ucPreset": 0,  # 设置 ucPreset 参数
        "qualityToggle": "true",  # 设置 qualityToggle 参数
        "sm": "false",  # 设置 sm 参数
        "sm_dyn": "false",  # 设置 sm_dyn 参数
        "dynamic_thresholding": "false",  # 设置 dynamic_thresholding 参数
        "controlnet_strength": 1,  # 设置 controlnet_strength 参数
        "legacy": "false",  # 设置 legacy 参数
        "add_original_image": "false",  # 设置 add_original_image 参数
        "uncond_scale": 1,  # 设置 uncond_scale 参数
        "cfg_rescale": 0,  # 设置 cfg_rescale 参数
        "noise_schedule": "native",  # 设置 noise_schedule 参数
        "negative_prompt": env_vars["negative_prompt"],  # 设置负面提示参数
    },
} 
将形如"false" "true" 改为 False True 即可解决问题 
不过之前官方API未更新是没有问题的
还是对大佬的工作表示感谢
