### ISSUE TITLE
脚本疑似失效

### ISSUE THREAD

**Issue by as8593189** [wochenlong/nai3_train#2]
使用脚本时，提示出现
“请求出现异常: HTTPSConnectionPool(host='image.novelai.net', port=443): Max retries exceeded with url: /ai/generate-image (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000018DA30FB460>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))”
连接超时。

但是使用postman做接口测试时发现，接口正常获取到zip数据。
![QQ截图20240210171653](https://github.com/wochenlong/nai3_train/assets/46948349/acedeaf9-a88e-4e30-8965-c48c3321dffb)

同样使用Java进行测试，依旧报“Caused by: java.net.ConnectException: Connection timed out: connect”连接超时错误。

由于相同的参数情况下，在postman中测试成功，排除token输入错误、请求头、体输入错误，怀疑官方是否有针对的屏蔽了相关本地API。

**Comment by as8593189** [comment]
没开全局代理的锅>_<。clash默认规则代理，这个时候，request不生效。

**Comment by wochenlong** [comment]
或许可以考虑在脚本内设置代理端口？
